export const GET_COMMENTS_BY_POST_START = 'GET_COMMENTS_BY_POST_START';
export const GET_COMMENTS_BY_POST_SUCCESS = 'GET_COMMENTS_BY_POST_SUCCESS';
export const GET_COMMENTS_BY_POST_FAILURE = 'GET_COMMENTS_BY_POST_FAILURE';